### ISSUE TITLE
KeyError: 'inserted-sequence'

### ISSUE THREAD

**Issue by lonphan** [ncbi/dbsnp#1]
python rsjson_demo.py -i refsnp-sample.json.gz
268
Traceback (most recent call last):
  File "rsjson_demo.py", line 86, in <module>
    printPlacements(rs_obj['primary_snapshot_data']['placements_with_allele'])
  File "rsjson_demo.py", line 63, in printPlacements
    if spdi['inserted-sequence'] != spdi['deletion-sequence']:
KeyError: 'inserted-sequence'

**Comment by lonphan** [comment]
fixed committed
